version: "3.5"

services:
  fluentd-forwarder-1:
    container_name: fluentd-forwarder-1
    build:
      context: ./FluentD/Forwarder
    depends_on:
      - fluentd-aggregator
    networks:
      - backend
    ports:
      - "24227:24224"

  fluentd-forwarder-2:
    build:
      context: ./FluentD/Forwarder
    container_name: fluentd-forwarder-2
    depends_on:
      - fluentd-aggregator
    networks:
      - backend
    ports:
      - "24226:24224"

  fluentd-aggregator:
    container_name: fluentd-aggregator
    build:
      context: ./FluentD/Aggregator
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "24225:24224"

  gameclient:
    container_name: gameclient
    build:
      context: .
      dockerfile: ./GameClient/Dockerfile
    depends_on:
      - gameserver
    ports:
      - "3000:80"
    networks:
      - backend

  gameserver:
    restart: always
    container_name: gameserver
    build:
      context: .
      dockerfile: ./GameServer/Dockerfile
    depends_on:
      - db
      - redis
      - fluentd-forwarder-1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8000
      - ASPNETCORE_URLS=http://*:8000
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - backend
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24227"
        fluentd-async-connect: "true"
        tag: server.game

  hiveserver:
    container_name: hiveserver
    build:
      context: .
      dockerfile: ./HiveAPIServer/Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - backend

  matchserver:
    build:
      context: .
      dockerfile: ./MatchAPIServer/Dockerfile
    container_name: matchserver
    depends_on:
      - redis
      - fluentd-forwarder-2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=9000
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - backend
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24226"
        fluentd-async-connect: "true"
        tag: server.match

  db:
    build:
      context: ./Database
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: comsooyoung!1
      MYSQL_USER: shanabunny
      MYSQL_PASSWORD: comsooyoung!1
      MYSQL_DATABASE: masterdb
    ports:
      - "3306:3306"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
