global:
  scrape_interval: 3s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
        # - targets: ["alertmanager:9093"]

rule_files:
  - "record.rules.yml"
#   - "alert.rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "gameserver"
    metrics_path: /metrics
    static_configs:
      - targets: ["gameserver:8001"]

  - job_name: "hiveserver"
    metrics_path: /metrics
    static_configs:
      - targets: ["hiveserver:8081"]

  - job_name: "matchserver"
    metrics_path: /metrics
    static_configs:
      - targets: ["matchserver:9001"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
